### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a top-down image, preferably png, of a car on the page
- [x] Change the background color of the page to a lovely shade of green
- [x] Add any necessary styling to position the car based on the example provided
