### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create an object to represent the car, with a `direction` property set to `east`
- [x] Add an event listener for `keydown` events
- [x] Rotate the racecar `img` element based on the pressed key (up, down, left, right)
- [x] Update the car object's `direction` property based on the pressed key
- [x] Add any necessary CSS to make the car smoothly rotate, like the example gif
