### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Add an engineOn property to your data model with a value of false.
- [x] Add an event listener for `keydown` events on the spacebar and change engineOn to true.
- [x] When engineOn becomes true, move the car a few pixels every 16 milliseconds.
