### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/driving-game#9]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update the spacedown keydown event listener so the car moves in the direction it's facing.
- [x] Add any necessary styling/functionality to make the car rotate in the correct direction each time.
- [x] Remove any unnecessary styling
